[platformio]
default_envs = tx_uno

[env]
platform = atmelavr
framework = arduino
lib_deps =
  nrf24/RF24
monitor_speed = 115200

[env:tx_uno]
board = uno
build_src_filter =
  +<tx_main.cpp>
  +<protocol.h>
  -<rx_main.cpp>

[env:tx_atmega328p_uart]
board = ATmega328P
board_build.f_cpu = 16000000L
upload_protocol = arduino
upload_speed = 57600
upload_port = COM7
build_src_filter =
  +<tx_main.cpp>
  +<protocol.h>
  -<rx_main.cpp>

[env:rx_nano]
board = nanoatmega328
upload_protocol = arduino
upload_speed = 57600
upload_port = COM10
monitor_port = COM10
build_src_filter =
  +<rx_main.cpp>
  +<protocol.h>
  -<tx_main.cpp>