[platformio]
default_envs = tx_atmega328p_uart

[env]
platform = atmelavr
framework = arduino
lib_deps =
  nrf24/RF24
monitor_speed = 115200

[env:tx_atmega328p_uart]
board = ATmega328P
board_build.f_cpu = 16000000L
upload_protocol = arduino
upload_speed = 57600
build_src_filter =
  +<tx_main.cpp>
  -<rx_main.cpp>
  -<ir_main.cpp>

[env:rx_nano]
platform = atmelavr
board = nanoatmega328new
framework = arduino
lib_deps =
  nrf24/RF24
upload_protocol = arduino
monitor_speed = 115200
build_src_filter =
  +<rx_main.cpp>
  -<tx_main.cpp>
  -<ir_main.cpp>

[env:ir_atmega328p_uart]
board = ATmega328P
board_build.f_cpu = 16000000L
upload_protocol = arduino
upload_speed = 57600
build_src_filter =
  +<ir_main.cpp>
  -<tx_main.cpp>
  -<rx_main.cpp>
